c1 = int(input("Course 1 hours: "))
g1 = int(input("Grade for course 1: "))
c2 = int(input("Course 2 hours: "))
g2 = int(input("Grade for course 2: "))
c3 = int(input("Course 3 hours: "))
g3 = int(input("Grade for course 3: "))
c4 = int(input("Course 4 hours: "))
g4 = int(input("Grade for course 4: "))
hrs = c1 + c2 + c3 + c4
qpts = (c1*g1)+(c2*g2)+(c3*g3)+(c4*g4)
print("Total hours: " + str(hrs))
print("Total quality points: " + str(qpts))
gpa = round((qpts / hrs),2)
print("Your GPA for this semester is " +str(gpa))